# Generated by Django 3.1.6 on 2021-03-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Organization', models.CharField(default=0, max_length=100)),
                ('username', models.CharField(default=0, max_length=25)),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('Total', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('ordered_date', models.DateField(auto_now=True)),
                ('delivered_date', models.CharField(max_length=50)),
                ('delivered', models.CharField(default='Notcompleted', max_length=50)),
                ('verified', models.CharField(default='NotVerified', max_length=50)),
            ],
        ),
    ]
