# Generated by Django 3.1.6 on 2021-03-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0002_auto_20210320_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='delivered_date',
            field=models.CharField(max_length=50),
        ),
    ]
