# Generated by Django 3.1.6 on 2021-03-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0003_auto_20210320_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='id',
            field=models.AutoField(default=1001, primary_key=True, serialize=False),
        ),
    ]
