# Generated by Django 3.1.6 on 2021-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0004_auto_20210320_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
