# Generated by Django 3.1.6 on 2021-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0006_ordering_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='payment',
        ),
        migrations.AlterField(
            model_name='ordering',
            name='verified',
            field=models.CharField(default='NoPayment', max_length=50),
        ),
    ]
