# Generated by Django 3.1.6 on 2021-03-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0007_auto_20210321_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='delivered',
            field=models.CharField(default='NotDelivered', max_length=50),
        ),
    ]
