# Generated by Django 3.1.6 on 2021-03-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0008_auto_20210321_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='verified',
            field=models.CharField(default='NotReceived', max_length=50),
        ),
    ]
