# Generated by Django 3.1.6 on 2021-04-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0009_auto_20210322_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='ordered_date',
            field=models.DateField(null=True),
        ),
    ]
