# Generated by Django 3.1.6 on 2021-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0017_auto_20210408_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='ordered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
