# Generated by Django 3.1.6 on 2021-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0019_auto_20210410_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='delivered_date',
            field=models.CharField(max_length=50),
        ),
    ]
