# Generated by Django 3.1.6 on 2021-04-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0021_auto_20210421_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='delivered_date',
            field=models.DateField(),
        ),
    ]
