# Generated by Django 3.1.6 on 2021-04-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0022_auto_20210422_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='delivered_date',
            field=models.CharField(max_length=50),
        ),
    ]
