# Generated by Django 3.1.6 on 2021-04-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordering', '0023_auto_20210422_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
