# Generated by Django 3.1.6 on 2021-03-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='details',
            new_name='colour',
        ),
    ]
